services:

  db:
    image: postgres:15
    container_name: spark_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SPARK
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: spark_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@spark_db:5432/SPARK
    ports:
      - "8000:8000"
    volumes:
      - ./qr_codes:/app/qr_codes

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: spark_frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"

volumes:
  postgres_data: